### ISSUE TITLE
IndexError in _is_dir()

### ISSUE THREAD

**Issue by jakev** [android-dtf/dtf#58]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/analyst/.dtf/modules//sysappdb", line 3261, in run
    if self.pull_odex(project_name, package_name) != 0:
  File "/home/analyst/.dtf/modules//sysappdb", line 3178, in pull_odex
    if self.adb.is_dir(app_oat_dir):
  File "/usr/local/lib/python2.7/dist-packages/dtf/adb.py", line 235, in is_dir
    elif line[0] == 'd':
IndexError: string index out of range
```

**Comment by jakev** [comment]
Not sure why this occurs, but the white space gets all messed up some times.

Normal:
```
[Tue Oct 10 15:29:19 PDT 2017] sysappdb-PullThread-5/I - Processing: 'com.android.bookmarkprovider' 
[Tue Oct 10 15:29:19 PDT 2017] sysappdb-PullThread-5/I - Getting APK file for 'com.android.bookmarkprovider' 
/system/app/BookmarkProvider/oat
['drwxr-xr-x root     root              2008-12-31 08:00 oat', '']
Checking is_dir() on : /system/app/BookmarkProvider/oat
Result is: drwxr-xr-x root     root              2008-12-31 08:00 oat
[Tue Oct 10 15:29:19 PDT 2017] sysappdb-PullThread-5/D - Using ODEX in oat/ 
[Tue Oct 10 15:29:19 PDT 2017] sysappdb-PullThread-5/D - Regular ART ODEX exists. 
[Tue Oct 10 15:29:19 PDT 2017] sysappdb-DbThread/I - Processing: com.android.bookmarkprovider 

```

Messed up:
```
[Tue Oct 10 15:27:48 PDT 2017] sysappdb-PullThread-4/I - Processing: 'com.facebook.system' 
[Tue Oct 10 15:27:48 PDT 2017] sysappdb-PullThread-4/I - Getting APK file for 'com.facebook.system' 
/data/app/com.facebook.system-1/oat
['', '', '', '', '', 'drwxrwx--x system   install           2017-10-10 11:44 oat', '']
Checking is_dir() on : /data/app/com.facebook.system-1/oat
Result is: 
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/analyst/.dtf/modules//sysappdb", line 3268, in run
    if self.pull_odex(project_name, package_name) != 0:
  File "/home/analyst/.dtf/modules//sysappdb", line 3152, in pull_odex
    if self.adb.is_dir(app_oat_dir):
  File "/usr/local/lib/python2.7/dist-packages/dtf/adb.py", line 238, in is_dir
    elif line[0] == 'd':
IndexError: string index out of range
```

Commit coming to address.

**Comment by jakev** [comment]
Fixed via: https://github.com/android-dtf/dtf/commit/d6633a5e37f044a193a4b6d6387384767c1f06b2
